name: Label Issues (Script Injection Example)
on:
  issues: #this workflow runs whenever a new issue is open for the GitHub Repository in which this code is stored
    types:
      - opened
jobs:
  assign-label:
    runs-on: ubuntu-latest
    steps:
      - name: Assign label #Performs only one step 
        env: 
          TITLE: ${{ github.event.issue.title }}
        run: |
          
          if [[ "$TITLE" == *"bug"* ]]; then
          echo "Issue is about a bug!"
          else
          echo "Issue is not about a bug"
          fi
#14 -- we extract the title of the issue that was created, and store it in a temporary variable ("issue_title") here in my shell.

#issue_title="${{ github.event.issue.title }}"